using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace XOPEB.Scaffolding
{
    public class CSharpGenerator : LanguageGenerator
    {
        public bool UseStringMaxLength { set; get; }

        public bool UseMeta { set; get; }

        public string Namespace { set; get; } = "XOPEB.Scaffolding";

        public string GetDatabaseClasses(IEnumerable<Table> tables)
        {
            var str = new StringBuilder();

            str.AppendLine("using System;");

            if (UseStringMaxLength && tables.Any(t => t.Columns.Any(c => c.Type == "string")))
            {
                str.AppendLine("using System.ComponentModel.DataAnnotations;");
            }

            var cmdParameters = Environment.GetCommandLineArgs();

            if (cmdParameters.Any(p => !p.Contains("XOPEB.Scaffolding")))
            {
                str.AppendLine("");

                str.AppendLine("// Generated by XOPEB.Scaffolding");

                str.AppendLine("// Parameters:");

                foreach (var parameter in cmdParameters.Where(p => !p.Contains("XOPEB.Scaffolding")))
                {
                    str.AppendLine($"//   {parameter}");
                }
            }

            str.AppendLine("");

            str.AppendLine($"namespace {Namespace}");

            str.AppendLine("{");

            if (UseMeta)
            {
                str.AppendLine($"\tusing XOPEB.DatabaseMeta;");

                str.AppendLine("");
            }

            foreach (var table in tables)
            {
                if (table != tables.First()) str.AppendLine("");

                var className = ToSingular(table.Name);

                str.AppendLine($"\tpublic partial class {className}");

                str.AppendLine("\t{");

                foreach (var column in table.Columns)
                {
                    if (column != table.Columns.First()) str.AppendLine("");

                    if (column.Type == "string" && UseStringMaxLength)
                    {
                        str.AppendLine($"\t\t[MaxLength(MaxLength{column.Name}_)]");
                    }

                    str.AppendLine($"\t\tpublic {column.Type}{(column.Nullable ? "?" : "")} {column.Name} {{ set; get; }} {(!UseStringMaxLength && column.Type == "string" ? $" // max {column.MaxLength}" : "")}");

                    if (column.Type == "string" && UseStringMaxLength)
                    {
                        str.AppendLine($"\t\tprivate const int MaxLength{column.Name}_ = {column.MaxLength};");
                        str.AppendLine($"\t\tpublic static int MaxLength{column.Name} => MaxLength{column.Name}_;");
                    }
                }

                str.AppendLine("\t}");

                if (UseMeta)
                {
                    str.AppendLine("");

                    str.AppendLine($"\tpublic class {table.Name}Table : TableMeta");

                    str.AppendLine("\t{");

                    foreach (var column in table.Columns)
                    {
                        if (column != table.Columns.First()) str.AppendLine("");

                        if (column.Type == "string")
                        {
                            str.AppendLine($"\t\tpublic StringColumnMeta {column.Name} {{ get; }} = new (\"{column.Name}\", nullable: {column.Nullable.ToDB()}, maxLength: {column.MaxLength}, unicode: {column.IsUnicode.ToDB()});");
                        }
                        else
                        {
                            str.AppendLine($"\t\tpublic ColumnMeta {column.Name} {{ get; }} = new (\"{column.Name}\", nullable: {column.Nullable.ToDB()});");
                        }
                    }

                    str.AppendLine("\t}");
                }
            }

            str.AppendLine("}");

            return str.ToString();
        }
    }

    public class LanguageGenerator
    {
        public static string ToSingular(string name)
        {
            if (name.EndsWith("ies"))
            {
                return name.Substring(0, name.Length - 3) + "y";
            }

            return name.TrimEnd('s');
        }
    }

    public static class Converters
    {
        public static string ToDB(this bool value)
        {
            return value ? "true" : "false";
        }
    }
}
